name: Get Link Speed
description: See details
title: "Get Link"
labels: ["Link"]
body:
  - type: markdown
    attributes:
      value: |
        Just enter the link and it will download and upload to another server.
  - type: input
    attributes:
      label: Link input
      description: |
        Input link `Url: http://file.com/path`
        Support: `Mega.nz`, `Direct`
      placeholder: "Url:"
      value: "Url: "
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Select upload server
      description: After downloading it will upload to the server you have chose
      options:
        - gofile.io
        - test
      default: 0
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Sau khi hoàn thành toàn bộ hãy ấn vào nút màu xanh lá để hoàn thành `Submit new issue`   

        Sau khi xây dựng xong bot sẽ gửi link download rom vào bài viết này.
        > Link download chỉ tồn tại trong thời gian ngắn 10 - 30 ngày
  - type: checkboxes
    attributes:
      label: Tùy chọn
      description: Tích vào ô bên dưới để thêm tính năng khi build rom.
      options:
        - label: "Thêm Tiếng Việt"
        - label: Test
          required: false

  - type: textarea
    attributes:
      label: Xoá ứng dụng
      description: |
        Tên thư mục ứng dụng ở /system/app/AiAsstVision, priv-app, product v.v
      render: shell
      value: "AiAsstVision "


      
