name: Get Link
description: See details
title: "Link Speed"
labels: ["Link"]
body:
  - type: markdown
    attributes:
      value: |
        Just enter the link and it will download and upload to another server.
  - type: input
    attributes:
      label: Link input
      description: |
        Input link Url: http://file_com/path
        Support: `Mega.nz`, `Direct`
      placeholder: "Url:"
      value: "Url: "
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Upload server
      description: After downloading it will upload to the server you have chose
      options:
        - Mixdrop
        - Transfer
        - Gofile
      default: 0
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        > Mixdrop - Unlimited/file
        > Gofile - Unlimited/file
        > Transfer - 10Gb/file
      
        Once completed, press the green button to complete `Submit new issue`   
        > The download link only lasts for a short time of 10 - 30 days, depending on the server 
