name: Mega-Link
on:
  workflow_dispatch:
    inputs:
      FEATURE:
        description: 'Import link mega: https://mega.nz/xxx'
        required: true
        default: ''
      SEVER1:
        description: 'Upload sever 1'
        required: false
        default: true
        type: boolean
      SEVER2:
        description: 'Upload sever 2'
        required: false
        default: false
        type: boolean
      SEVER3:
        description: 'Upload sever 3, import token, will upload to the website: gbdrive.xyz/drive'
        required: false
        default: ''

permissions: write-all
jobs:
  build:
    name: 'See-progress'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Mega
        run: sudo apt-get install megatools
      - name: Download
        env:
          FEATURE: ${{ inputs.FEATURE }}
          SEVER1: ${{ inputs.SEVER1 }}
          SEVER2: ${{ inputs.SEVER2 }}
          SEVER3: ${{ inputs.SEVER3 }}
        run: |
          # kakathic
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          mkdir -p Up
          cd Up
          megadl "$FEATURE"
      - name: Upload 1
        if: inputs.SEVER1 == true
        run: |
          # kakathic
          HOME="$GITHUB_WORKSPACE"
          cd Up
          url1="$(ls)"
          url2="$(curl -s https://api.gofile.io/getServer | jq -r .data.server)"
          eval "curl -F file=@\""$url1"\" https://"$url2".gofile.io/uploadFile > $HOME/1.json"
          echo
          echo "Name: $(cat $HOME/1.json | jq -r .data.fileName)"
          echo "Link download: $(cat $HOME/1.json | jq -r .data.downloadPage)"
          echo "Md5: $(cat $HOME/1.json | jq -r .data.md5)"
      - name: Upload 2
        if: inputs.SEVER2 == true
        uses: actions/upload-artifact@v3
        with:
          name: Link-Speed
          path: Up/*
          retention-days: 2
      - name: Upload 3
        if: inputs.SEVER3
        run: |
          # kakathic
          cd Up
          url1="$(ls)"
          eval "curl https://gbdrive.xyz/api/v1/uploads -H 'Authorization: Bearer "$SEVER3"' -F file=@\""$url1"\" | jq"
          
